### ISSUE TITLE
[Bug]: QueryResult is not a Bio object

### ISSUE THREAD

**Issue by anderdnavarro** [ylab-hi/pxblat#162]
### What happened?

Hi!

I am trying to access the results after `client.query` using the Bio module instead of parsing the results as a list. In the [tutorial](https://pxblat.readthedocs.io/en/latest/tutorial.html#query-result) you say that "The query result is the same as QueryResult of Bio.", however I can't access the data that way:

```python
ret1 = client.query("GAAGAAGCTGGGATTGGAATGCAGGTCTCTTGCGGGATGTGGTGTGGGAGGAGAATGCACAAATGGACAGAGTGGGGGTTGGGGGCTGGGAAAGAGCTAAGGACCAGGGCAGGAGGGGATTCAAGAGACTGAGTAGGGCAGCTAGCTAGTTCCTGGGAGCTCTTCCCTTGTCATCTCATCAGTTTGGACTCCTCGAACAATTC")

# Command
ret1
# Result
[QueryResult(id='/tmp/tmpdd6dm058', 4 hits)]

# Command
type(ret1)
# Result
list

# Command
type(ret1[0])
# Result
Bio.SearchIO._model.query.QueryResul

# Command
qresults = SearchIO.parse(ret1[0], 'blast-xml') #I tried different formats
qresults
# Result
<generator object parse at 0x2b500bf297a0>

# Command
type(qresults)
# Result
generator

# Command
next(qresults)
# Result
TypeError: expected str, bytes or os.PathLike object, not QueryResult

# Command
qresults[0]
# Result
TypeError: 'generator' object is not subscriptable

# Command
for item in qresults:
    print(item)
# Result
TypeError: expected str, bytes or os.PathLike object, not QueryResult

# Command
for item in qresults:
    type(item)
# Result
TypeError: expected str, bytes or os.PathLike object, not QueryResult
```

I don't know if I'm doing something wrong, but I tried everything I knew.

Thank you very much! This program is very useful!!!

Best,
Ander

### Version

v0.3.4

### What platform are you working on?

Linux

### Code of Conduct

- [X] #163

**Comment by cauliyang** [comment]
Hi @anderdnavarro, 

Thanks for your report! 

```python
ret1 = client.query("GAAGAAGCTGGGATTGGAATGCAGGTCTCTTGCGGGATGTGGTGTGGGAGGAGAATGCACAAATGGACAGAGTGGGGGTTGGGGGCTGGGAAAGAGCTAAGGACCAGGGCAGGAGGGGATTCAAGAGACTGAGTAGGGCAGCTAGCTAGTTCCTGGGAGCTCTTCCCTTGTCATCTCATCAGTTTGGACTCCTCGAACAATTC")

# Command
ret1
# Result
[QueryResult(id='/tmp/tmpdd6dm058', 4 hits)]
```

`ret1` is a `list` of `QueryResult` according to your example. Hence we do not need to use `SearchIO.parse(ret1[0], 'blast-xml')` to parse again. `pxblat` already did that.  Hence, we can check the result via:

```python
for res in ret1:
	for hsp in res.hsps:
		print(hsp)
```

or do the same things as Toturial said.

```python
>>> qresult = ret1[0]
>>> first_hit = qresult[0]
>>> first_hit
```

Also, the [notebook](https://colab.research.google.com/drive/1TXb9GBmYa2EYezwBKbD-y9Xg6MC2gL36) shows several examples of how to manipulate results. I will clarify the toturial later and Hopefully helpful!

**Comment by anderdnavarro** [comment]
Thanks @cauliyang! I'll do it like this.

I just thought there was another more specific way to access the data with `Bio`. Sorry for the confusion.

**Comment by cauliyang** [comment]
@anderdnavarro, please let me know if the problem is still here after you tried or which part of `pxblat` still bothers you. Thanks for sharing and have a good weekend!

**Comment by anderdnavarro** [comment]
@cauliyang I could solve the problem following the Notebook:

```python
for query in ret1:
    for hit in query.hsps:
        print(f"Chrom={hit.hit_id} Region={hit.hit_range} SeqLen={query.seq_len} Match={hit.match_num}")
```
Now I can filter it to find the best result in an easy way, thanks!

Once I understood how the object is constructed it was easy to do it, although I would remove the `Bio` explanation from the tutorial since it's no longer used and can be a bit confused, and would replace it by the 3-4 commands you have in the Notebook.

You too, have a nice weekend!!

**Comment by cauliyang** [comment]
happy to hear that you resolved that! that is a good point and I will clarify the tutorial.

**Comment by anderdnavarro** [comment]
Hi again @cauliyang, I wrote this small function to display a table similar to the one we can find in the blat web server:

```python
def print_results(results):
    df = pd.DataFrame(columns=["Score", "Chrom", "Start", "End", "Strand", "SeqLen", "Match", "SPAN"])
    for query in results:
        for hit in query.hsps:
            try:
                df.loc[len(df)] = [hit.score, hit.hit_id, hit.hit_start, hit.hit_end, hit.query_strand, query.seq_len, hit.match_num, hit.hit_span]
            except ValueError:
                df.loc[len(df)] = [hit.score, hit.hit_id, hit.hit_start, hit.hit_end, hit[0].query_strand, query.seq_len, hit.match_num, hit.hit_span]
    return(df.sort_values(by='Score', ascending=False))
```

Don't know why when there is more than one fragment for one hit, the `hit.query_strand` raises an error if I don't use `hit[0]`, but it works.

I share it, in case you find it useful.

**Comment by cauliyang** [comment]
Hi @anderdnavarro, really appreciate your sharing. The error is raised by `biopython`
https://github.com/biopython/biopython/blob/1087dffd629bf15c17317d62d4089042e05ce973/Bio/SearchIO/_utils.py#L74C19-L74C19. 

In `biopython`, it uses https://github.com/biopython/biopython/blob/1087dffd629bf15c17317d62d4089042e05ce973/Bio/SearchIO/_model/_base.py#L59C5-L65C45 to fetch strands. It is a kind of "the bug is a feature" : ).

**Comment by anderdnavarro** [comment]
I see, now it makes sense! I was wondering why an error occurs if it is always the same strand.

Thanks!!
