### ISSUE TITLE
public to bioconda for x86 and aarch64 

### ISSUE THREAD

**Issue by cauliyang** [ylab-hi/pxblat#27]
# Plan 

- [x] add the lib to bioconda 
~- [ ] automate the process to bump the version and submit pr to Bioconda~ 
- [ ] add building target of aarch64

**Comment by cauliyang** [comment]
https://github.com/bioconda/bioconda-recipes/pull/41165

**Comment by cauliyang** [comment]
It has been merged but cannot be found in bioconda channel

**Comment by mencian** [comment]
Hello @cauliyang, I have edit the PxBLAT bioconda recipe [here](https://github.com/bioconda/bioconda-recipes/pull/41895) and PxBLAT is now in the [bioconda channel](https://anaconda.org/bioconda/pxblat).

**Comment by cauliyang** [comment]
Hi @mencian , sorry for the late reply. I really appreciate your great help, and many thanks for your contribution and time!

**Comment by cauliyang** [comment]
Currently, conda only installs pxblat with python=3.11.
